head <- read.table("./Week1Project/household_power_consumption.txt", sep=";", nrows = 1, stringsAsFactors = FALSE)
df <- read.table("./Week1Project/household_power_consumption.txt", sep=";", col.names = head, na.strings = "?", skip=grep("^1/2/2007", readLines("./Week1Project/household_power_consumption.txt"))[1]-1,nrow=length(grep("^1/2/2007|^2/2/2007", readLines("./Week1Project/household_power_consumption.txt"))))
df$NewDate <- with(df, strptime(paste(Date, Time), format = "%d/%m/%Y %H:%M:%S"))
png("plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
with(df, plot(NewDate, Global_active_power, type = "n", xlab = "", ylab = "Global Active Power (kilowatts)"))
with(df, lines(NewDate, Global_active_power, type = "l"))
with(df, plot(NewDate, Voltage, type="n", xlab = "datetime", ylab = "Voltage"))
with(df, lines(NewDate, Voltage, type = "l"))
with(df, plot(NewDate, Sub_metering_1, type="n", xlab = "", ylab = "Energy sub metering"))
with(df, lines(NewDate, Sub_metering_1, type = "l"))
with(df, lines(NewDate, Sub_metering_2, type = "l", col="red"))
with(df, lines(NewDate, Sub_metering_3, type = "l", col="blue"))
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lwd = 1, bty = "n", cex = 0.75)
with(df, plot(NewDate, Global_reactive_power, type = "n", xlab = "datetime"))
with(df, lines(NewDate, Global_reactive_power, type = "l"))
dev.off()